baseurl = "https://guzmanramon04.netlify.app/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Ramon Guzman"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Ramon Guzman"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "About Me"
        name = "About Me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "Resume"
        name = "Resume"
        url = "/resume"
      [[languages.en.menu.main]]
        identifier = "Contact"
        name = "Contact"
        url = "/contact"
      [[languages.en.menu.main]]
        identifier = "contact2"
        name = "contact2"
        url = "/contact2"
        
